# Generated by Django 5.0.7 on 2024-07-11 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poll', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='polloption',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
        migrations.AddField(
            model_name='vote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.participant'),
        ),
        migrations.AddField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.polloption'),
        ),
    ]
