# Generated by Django 5.0.7 on 2024-07-26 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_alter_polloption_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='poll_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poll.polloption'),
        ),
    ]
