import { Inter } from "next/font/google";

import "./globals.css";
import Message from "@/components/Message";
import { MessageProvider } from "@/context/MessageContext";
import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/NavBar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <MessageProvider>

        <body className={inter.className}>
          <AuthProvider>


            <NavBar></NavBar>
            {children}
          </AuthProvider>
          <Message></Message>
        </body>
      </MessageProvider>
    </html>
  );
}
